-- Migration: Add outfit_signature column and index for duplicate detection
-- Created: 2025-11-13
-- Description: Adds a canonical signature column to enable fast duplicate outfit detection

-- Step 1: Add the outfit_signature column (nullable initially for backfilling)
ALTER TABLE outfits
ADD COLUMN IF NOT EXISTS outfit_signature TEXT;

-- Step 2: Create composite index for fast lookups
-- This index enables fast queries: WHERE user_id = ? AND outfit_signature = ?
CREATE INDEX IF NOT EXISTS idx_outfits_user_signature 
ON outfits(user_id, outfit_signature);

-- Step 3: Backfill existing outfits with signatures
-- This generates signatures for all existing outfits by sorting and joining their clothing_item_ids
UPDATE outfits
SET outfit_signature = (
  SELECT string_agg(id::text, ',' ORDER BY id::text)
  FROM unnest(clothing_item_ids) AS id
)
WHERE outfit_signature IS NULL;

-- Step 4: (Optional) Add NOT NULL constraint after backfill completes
-- Uncomment the following line after verifying all rows have signatures:
-- ALTER TABLE outfits ALTER COLUMN outfit_signature SET NOT NULL;

-- Note: The signature is generated by:
-- 1. Sorting clothing_item_ids alphabetically
-- 2. Joining with comma delimiter
-- Example: ["id3", "id1", "id2"] -> "id1,id2,id3"

